spring:
  datasource:
    url: jdbc:tc:postgresql:16:///notesdb_test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    show-sql: false
  flyway:
    enabled: true

app:
  jwt:
    secret: dGVzdC1zZWNyZXQta2V5LW11c3QtYmUtYXQtbGVhc3QtMzItYnl0ZXM=
    access-expiry-ms: 60000
    refresh-expiry-ms: 300000
